// Generated by scripts/build-mall-list.ts - do not hand-edit the entries,
// re-run the script instead. Each mall was validated to have real Google
// Popular Times coverage before being added here (see the conversation /
// mall-validation-report.json for the methodology). Coordinates come from
// OneMap's free search API. carparkDevelopments, where present, names the
// matching live LTA carpark Development record(s) (matched by proximity,
// not by name) so the app can attach raw available-lot counts as a bonus
// stat without duplicating the venue as a second pin.
export interface MallEntry {
  id: string;
  name: string;
  address: string;
  lat: number;
  lng: number;
  carparkDevelopments?: string[];
}

export const MALLS: MallEntry[] = [
  { id: "313-somerset", name: "313@somerset", address: "313 ORCHARD ROAD 313 @ SOMERSET SINGAPORE 238895", lat: 1.301014364040584, lng: 103.8383606644851, carparkDevelopments: ["313@Somerset"] },
  { id: "alexandra-retail-centre", name: "Alexandra Retail Centre", address: "460 ALEXANDRA ROAD ALEXANDRA RETAIL CENTRE (ARC)", lat: 1.27414893629255, lng: 103.8013994166651 },
  { id: "bugis-junction", name: "Bugis Junction", address: "200 VICTORIA STREET BUGIS JUNCTION SINGAPORE 188021", lat: 1.299112874758746, lng: 103.8554111737572 },
  { id: "bugis", name: "Bugis+", address: "201 VICTORIA STREET BUGIS+ SINGAPORE 188067", lat: 1.299603689902971, lng: 103.8542423474883, carparkDevelopments: ["Bugis+"] },
  { id: "capitol-piazza", name: "Capitol Piazza", address: "13 STAMFORD ROAD CAPITOL PIAZZA SINGAPORE 178905", lat: 1.293078847631338, lng: 103.8512619821488 },
  { id: "cathay-cineleisure-orchard", name: "Cathay Cineleisure Orchard", address: "8 GRANGE ROAD CATHAY CINELEISURE ORCHARD SINGAPORE 239695", lat: 1.30152101873534, lng: 103.8364296550156, carparkDevelopments: ["Cineleisure"] },
  { id: "the-centrepoint", name: "The Centrepoint", address: "176 ORCHARD ROAD AMB AQUATIC HUB THE CENTREPOINT", lat: 1.302303823328855, lng: 103.8397581729686, carparkDevelopments: ["Centrepoint"] },
  { id: "city-square-mall", name: "City Square Mall", address: "180 KITCHENER ROAD CITY SQUARE MALL SINGAPORE 208539", lat: 1.311421031076843, lng: 103.8566240199911 },
  { id: "citylink-mall", name: "CityLink Mall", address: "1 RAFFLES LINK CITYLINK MALL SINGAPORE 039393", lat: 1.292777731289308, lng: 103.854173501417 },
  { id: "chinatown-point", name: "Chinatown Point", address: "133 NEW BRIDGE ROAD CHINATOWN POINT SINGAPORE 059413", lat: 1.284998828474023, lng: 103.8446970811421 },
  { id: "far-east-plaza", name: "Far East Plaza", address: "14 SCOTTS ROAD FAR EAST PLAZA SINGAPORE 228213", lat: 1.307176980711882, lng: 103.833792932243, carparkDevelopments: ["Far East Plaza"] },
  { id: "funan", name: "Funan", address: "107 NORTH BRIDGE ROAD FUNAN SINGAPORE 179105", lat: 1.291347596977954, lng: 103.8499897900843, carparkDevelopments: ["Funan Mall"] },
  { id: "great-world", name: "Great World", address: "1 KIM SENG PROMENADE GREAT WORLD CITY SINGAPORE 237994", lat: 1.293422726500028, lng: 103.8320221466545 },
  { id: "ion-orchard", name: "ION Orchard", address: "2 ORCHARD TURN ION ORCHARD SINGAPORE 238801", lat: 1.303979741445055, lng: 103.832032328465, carparkDevelopments: ["ION Orchard"] },
  { id: "jelita-mall", name: "Jelita Mall", address: "293 HOLLAND ROAD JELITA MALL SINGAPORE 278628", lat: 1.317545559398872, lng: 103.7858505425145 },
  { id: "junction-8", name: "Junction 8", address: "9 BISHAN PLACE JUNCTION 8 SINGAPORE 579837", lat: 1.350481253450499, lng: 103.848760473211, carparkDevelopments: ["Junction 8"] },
  { id: "lucky-plaza", name: "Lucky Plaza", address: "304 ORCHARD ROAD LUCKY PLAZA SINGAPORE 238863", lat: 1.304506046466357, lng: 103.8339623398165, carparkDevelopments: ["Tang Plaza"] },
  { id: "marina-square", name: "Marina Square", address: "6 RAFFLES BOULEVARD MARINA SQUARE SINGAPORE 039594", lat: 1.291855332730248, lng: 103.8585780890598 },
  { id: "millenia-walk", name: "Millenia Walk", address: "9 RAFFLES BOULEVARD MILLENIA WALK SINGAPORE 039596", lat: 1.292605444624933, lng: 103.8597249444427, carparkDevelopments: ["Millenia Singapore"] },
  { id: "mustafa-centre", name: "Mustafa Centre", address: "145 SYED ALWI ROAD MUSTAFA CENTRE SINGAPORE 207704", lat: 1.310112131903957, lng: 103.8552908739255 },
  { id: "ngee-ann-city", name: "Ngee Ann City", address: "391 ORCHARD ROAD NGEE ANN CITY SINGAPORE 238872", lat: 1.30224168528687, lng: 103.8351819122968, carparkDevelopments: ["Ngee Ann City"] },
  { id: "orchard-central", name: "Orchard Central", address: "181 ORCHARD ROAD ORCHARD CENTRAL SINGAPORE 238896", lat: 1.300838908392453, lng: 103.8394347338989, carparkDevelopments: ["Orchard Central"] },
  { id: "orchard-gateway", name: "Orchard Gateway", address: "277 ORCHARD ROAD ORCHARD GATEWAY", lat: 1.300443252795456, lng: 103.8394427800415 },
  { id: "palais-renaissance", name: "Palais Renaissance", address: "390 ORCHARD ROAD PALAIS RENAISSANCE SINGAPORE 238871", lat: 1.306654845431923, lng: 103.8295880451874 },
  { id: "the-paragon", name: "The Paragon", address: "290 ORCHARD ROAD THE PARAGON SINGAPORE 238859", lat: 1.303872308799947, lng: 103.8358575454689, carparkDevelopments: ["Paragon"] },
  { id: "people-s-park-centre", name: "People's Park Centre", address: "101 UPPER CROSS STREET PEOPLE'S PARK CENTRE SINGAPORE 058357", lat: 1.285770099818055, lng: 103.8439801228374 },
  { id: "plaza-singapura", name: "Plaza Singapura", address: "68 ORCHARD ROAD PLAZA SINGAPURA SINGAPORE 238839", lat: 1.300747709639166, lng: 103.8450475734307, carparkDevelopments: ["Plaza Singapura","The Atrium@Orchard"] },
  { id: "raffles-city", name: "Raffles City", address: "252 NORTH BRIDGE ROAD RAFFLES CITY SHOPPING CENTRE", lat: 1.293893578633135, lng: 103.8531199046559, carparkDevelopments: ["Raffles City"] },
  { id: "sim-lim-square", name: "Sim Lim Square", address: "1 ROCHOR CANAL ROAD SIM LIM SQUARE SINGAPORE 188504", lat: 1.303024260571796, lng: 103.8530378140664 },
  { id: "square-2", name: "Square 2", address: "10 SINARAN DRIVE SQUARE 2 SINGAPORE 307506", lat: 1.320705109568455, lng: 103.8441607096606 },
  { id: "suntec-city", name: "Suntec City", address: "3 TEMASEK BOULEVARD GOLDEN VILLAGE (GV SUNTEC CITY)", lat: 1.29485990186642, lng: 103.860333693777 },
  { id: "tanjong-pagar-centre", name: "Tanjong Pagar Centre", address: "5 WALLICH STREET TANJONG PAGAR CENTRE SINGAPORE 078883", lat: 1.276583606968434, lng: 103.8459363035937 },
  { id: "tiong-bahru-plaza", name: "Tiong Bahru Plaza", address: "302 TIONG BAHRU ROAD TIONG BAHRU PLAZA SINGAPORE 168732", lat: 1.286458894728254, lng: 103.8270152561934 },
  { id: "thomson-plaza", name: "Thomson Plaza", address: "301 UPPER THOMSON ROAD THOMSON PLAZA SINGAPORE 574408", lat: 1.354669024964243, lng: 103.830919782333 },
  { id: "vivocity", name: "VivoCity", address: "1 HARBOURFRONT WALK VIVOCITY SINGAPORE 098585", lat: 1.264293167839738, lng: 103.8223046936493, carparkDevelopments: ["VivoCity P3","VivoCity P2"] },
  { id: "wheelock-place", name: "Wheelock Place", address: "501 ORCHARD ROAD WHEELOCK PLACE SINGAPORE 238880", lat: 1.304676287302523, lng: 103.8306420275763, carparkDevelopments: ["Wheelock Place"] },
  { id: "wisma-atria", name: "Wisma Atria", address: "435 ORCHARD ROAD WISMA ATRIA SINGAPORE 238877", lat: 1.303704774261485, lng: 103.8332057528079, carparkDevelopments: ["Wisma Atria"] },
  { id: "bedok-mall", name: "Bedok Mall", address: "311 NEW UPPER CHANGI ROAD BEDOK MALL SINGAPORE 467360", lat: 1.324736327847299, lng: 103.929256259998, carparkDevelopments: ["Bedok Mall"] },
  { id: "century-square", name: "Century Square", address: "2 TAMPINES CENTRAL 5 CENTURY SQUARE SINGAPORE 529509", lat: 1.35236829566862, lng: 103.9438123022526 },
  { id: "changi-city-point", name: "Changi City Point", address: "5 CHANGI BUSINESS PARK CENTRAL 1 CHANGI CITY POINT", lat: 1.334036379027078, lng: 103.9629176155306 },
  { id: "downtown-east", name: "Downtown East", address: "1 PASIR RIS CLOSE COSTA SANDS RESORT (DOWNTOWN EAST) SINGAPORE 519599", lat: 1.379127178780095, lng: 103.9554447581442 },
  { id: "eastpoint-mall", name: "Eastpoint Mall", address: "3 SIMEI STREET 6 EASTPOINT MALL SINGAPORE 528833", lat: 1.342705923555769, lng: 103.9530246182335 },
  { id: "jewel-changi-airport", name: "Jewel Changi Airport", address: "78 AIRPORT BOULEVARD JEWEL CHANGI AIRPORT SINGAPORE 819666", lat: 1.360341006610217, lng: 103.9890775502096 },
  { id: "katong-shopping-centre", name: "Katong Shopping Centre", address: "865 MOUNTBATTEN ROAD KATONG SHOPPING CENTRE SINGAPORE 437844", lat: 1.304097311509515, lng: 103.9015159169702 },
  { id: "kallang-wave-mall", name: "Kallang Wave Mall", address: "1 STADIUM PLACE KALLANG WAVE MALL SINGAPORE 397628", lat: 1.30307515150401, lng: 103.8731497075906 },
  { id: "leisure-park-kallang", name: "Leisure Park Kallang", address: "5 STADIUM WALK LEISURE PARK KALLANG SINGAPORE 397693", lat: 1.302301084052293, lng: 103.8764739758827 },
  { id: "our-tampines-hub", name: "Our Tampines Hub", address: "1 TAMPINES WALK HAWKER CENTRE @ OUR TAMPINES HUB", lat: 1.35354740485205, lng: 103.9403811045466 },
  { id: "parkway-parade", name: "Parkway Parade", address: "80 MARINE PARADE ROAD PARKWAY PARADE SINGAPORE 449269", lat: 1.301069755063101, lng: 103.9052794915233 },
  { id: "paya-lebar-quarter", name: "Paya Lebar Quarter", address: "10 PAYA LEBAR ROAD PAYA LEBAR QUARTER SINGAPORE 409057", lat: 1.317708868989965, lng: 103.8934146635971 },
  { id: "paya-lebar-square", name: "Paya Lebar Square", address: "60 PAYA LEBAR ROAD PAYA LEBAR SQUARE SINGAPORE 409051", lat: 1.318814870076511, lng: 103.8925807785135 },
  { id: "singpost-centre", name: "SingPost Centre", address: "10 EUNOS ROAD 8 SINGAPORE POST CENTRE SINGAPORE 408600", lat: 1.318996669036639, lng: 103.8948949159614 },
  { id: "tampines-1", name: "Tampines 1", address: "203 TAMPINES STREET 21 PCF TAMPINES EAST 3-IN-1 FAMILY CENTRE (STUDENT CARE)", lat: 1.352227945045802, lng: 103.9524374430853 },
  { id: "tampines-mall", name: "Tampines Mall", address: "4 TAMPINES CENTRAL 5 TAMPINES MALL SINGAPORE 529510", lat: 1.352527372785196, lng: 103.9446987510717, carparkDevelopments: ["Tampines Mall"] },
  { id: "white-sands", name: "White Sands", address: "2 PASIR RIS STREET 11 LEARNING LEAP PTE LTD (WHITE SANDS PRIMARY SCHOOL)", lat: 1.365636109416956, lng: 103.9608618146777 },
  { id: "pasir-ris-mall", name: "Pasir Ris Mall", address: "7 PASIR RIS CENTRAL PASIR RIS MALL SINGAPORE 519612", lat: 1.373824377794677, lng: 103.9487488736156 },
  { id: "amk-hub", name: "AMK Hub", address: "53 ANG MO KIO AVENUE 3 AMK HUB SINGAPORE 569933", lat: 1.369389226903445, lng: 103.8484779659393 },
  { id: "canberra-plaza", name: "Canberra Plaza", address: "132 CANBERRA VIEW 7 ELEVEN CANBERRA PLAZA", lat: 1.443352663745675, lng: 103.8309390452592 },
  { id: "causeway-point", name: "Causeway Point", address: "1 WOODLANDS SQUARE CAUSEWAY POINT SINGAPORE 738099", lat: 1.436070065080311, lng: 103.7859815242531 },
  { id: "northpoint-city", name: "Northpoint City", address: "930 YISHUN AVENUE 2 NORTHPOINT CITY SINGAPORE 769098", lat: 1.429698486262892, lng: 103.8357764914675 },
  { id: "sembawang-shopping-centre", name: "Sembawang Shopping Centre", address: "604 SEMBAWANG ROAD SEMBAWANG SHOPPING CENTRE SINGAPORE 758459", lat: 1.441824706757328, lng: 103.8248452072371 },
  { id: "sun-plaza", name: "Sun Plaza", address: "30 SEMBAWANG DRIVE SUN PLAZA SINGAPORE 757713", lat: 1.44819535371132, lng: 103.8195021271551 },
  { id: "compass-one", name: "Compass One", address: "1 SENGKANG SQUARE COMPASS ONE SINGAPORE 545078", lat: 1.39205314156707, lng: 103.8950705438402 },
  { id: "heartland-mall", name: "Heartland Mall", address: "205 HOUGANG STREET 21 HEARTLAND MALL-KOVAN SINGAPORE 530205", lat: 1.359541773255625, lng: 103.8851673727259 },
  { id: "hougang-mall", name: "Hougang Mall", address: "90 HOUGANG AVENUE 10 HOUGANG MALL SINGAPORE 538766", lat: 1.372491186358026, lng: 103.8937740666245 },
  { id: "nex", name: "NEX", address: "23 SERANGOON CENTRAL NEX SINGAPORE 556083", lat: 1.350769352578452, lng: 103.8722961438613 },
  { id: "punggol-plaza", name: "Punggol Plaza", address: "168 PUNGGOL FIELD PUNGGOL PLAZA SINGAPORE 820168", lat: 1.39423719717118, lng: 103.913047323223 },
  { id: "punggol-coast-mall", name: "Punggol Coast Mall", address: "84 PUNGGOL WAY 84 PUNGGOL WAY - COCOA PODS BY THE COCOA TREES PUNGGOL COAST MALL", lat: 1.414553312413388, lng: 103.9082353100278 },
  { id: "the-seletar-mall", name: "The Seletar Mall", address: "33 SENGKANG WEST AVENUE THE SELETAR MALL SINGAPORE 797653", lat: 1.391470153746278, lng: 103.876125507257 },
  { id: "waterway-point", name: "Waterway Point", address: "83 PUNGGOL CENTRAL SHAW THEATRES WATERWAY POINT", lat: 1.406536116905548, lng: 103.9019881717096 },
  { id: "northshore-plaza-i", name: "Northshore Plaza I", address: "407 NORTHSHORE DRIVE 365 JUICES BAR NORTHSHORE PLAZA I", lat: 1.416848147385155, lng: 103.9021398350904 },
  { id: "northshore-plaza-ii", name: "Northshore Plaza II", address: "418 NORTHSHORE DRIVE 4FINGERS CRIPSY CHICKEN NORTHSHORE PLAZA II", lat: 1.418028033862532, lng: 103.9012765710931 },
  { id: "anchorvale-village", name: "Anchorvale Village", address: "339 ANCHORVALE ROAD 7 ELEVEN ANCHORVALE VILLAGE", lat: 1.396821323448975, lng: 103.8884392117688 },
  { id: "sengkang-grand-mall", name: "Sengkang Grand Mall", address: "70 COMPASSVALE BOW SENGKANG GRAND MALL SINGAPORE 544692", lat: 1.382981632033452, lng: 103.8927210077455 },
  { id: "bukit-panjang-plaza", name: "Bukit Panjang Plaza", address: "1 JELEBU ROAD BUKIT PANJANG PLAZA SINGAPORE 677743", lat: 1.379920451762434, lng: 103.764357180314, carparkDevelopments: ["Bt Panjang Plaza"] },
  { id: "fajar-shopping-centre", name: "Fajar Shopping Centre", address: "445 FAJAR ROAD 7-11 FAJAR SHOPPING CENTRE", lat: 1.383999908729805, lng: 103.7704925444304 },
  { id: "greenridge-shopping-centre", name: "Greenridge Shopping Centre", address: "524A JELAPANG ROAD AMETHYST PASTRY & CAKES GREENRIDGE SHOPPING CENTRE", lat: 1.385177143268358, lng: 103.766389180657 },
  { id: "hillion-mall", name: "Hillion Mall", address: "17 PETIR ROAD HILLION MALL SINGAPORE 678278", lat: 1.37843100827587, lng: 103.7628427898765 },
  { id: "imm", name: "IMM", address: "2 JURONG EAST STREET 21 IMM BUILDING SINGAPORE 609601", lat: 1.334875261180072, lng: 103.7468947730077, carparkDevelopments: ["IMM Building"] },
  { id: "jem", name: "Jem", address: "50 JURONG GATEWAY ROAD JEM SINGAPORE 608549", lat: 1.333293344734624, lng: 103.743278742341 },
  { id: "junction-10", name: "Junction 10", address: "1 WOODLANDS ROAD JUNCTION 10 SINGAPORE 677899", lat: 1.38033681049385, lng: 103.7601678834385 },
  { id: "jurong-point", name: "Jurong Point", address: "399 YUNG SHENG ROAD FAMILY POINT CLINIC AND SURGERY TAMAN JURONG SHOPPING CENTRE", lat: 1.334844874712597, lng: 103.7204620242775 },
  { id: "hillv2", name: "HillV2", address: "4 HILLVIEW RISE HILLV2 SINGAPORE 667979", lat: 1.362674508280243, lng: 103.7641729200599 },
  { id: "limbang-shopping-centre", name: "Limbang Shopping Centre", address: "534 CHOA CHU KANG STREET 51 5B LIMBANG PTE LTD LIMBANG SHOPPING CENTRE", lat: 1.392355940124954, lng: 103.7432205400243 },
  { id: "lot-one", name: "Lot One", address: "21 CHOA CHU KANG AVENUE 4 SHAW THEATRES LOT ONE", lat: 1.38507, lng: 103.74524, carparkDevelopments: ["Lot One"] },
  { id: "pioneer-mall", name: "Pioneer Mall", address: "638 JURONG WEST STREET 61 7-11 PIONEER MALL", lat: 1.34191503828199, lng: 103.6973574965404 },
  { id: "queensway-shopping-centre", name: "Queensway Shopping Centre", address: "1 QUEENSWAY QUEENSWAY SHOPPING CENTRE SINGAPORE 149053", lat: 1.287595189398704, lng: 103.8033972877883 },
  { id: "the-clementi-mall", name: "The Clementi Mall", address: "3155 COMMONWEALTH AVENUE WEST THE CLEMENTI MALL SINGAPORE 129588", lat: 1.314896196393653, lng: 103.764423054189 },
  { id: "the-rail-mall", name: "The Rail Mall", address: "384 UPPER BUKIT TIMAH ROAD THE RAIL MALL SINGAPORE 678042", lat: 1.35781103484491, lng: 103.7680806329584 },
  { id: "teck-whye-shopping-centre", name: "Teck Whye Shopping Centre", address: "137 TECK WHYE LANE TECK WHYE SHOPPING CENTRE SINGAPORE 680137", lat: 1.380047529753983, lng: 103.7524838411989 },
  { id: "the-star-vista", name: "The Star Vista", address: "1 VISTA EXCHANGE GREEN THE STAR VISTA", lat: 1.306970440383233, lng: 103.7884202741146 },
  { id: "west-coast-plaza", name: "West Coast Plaza", address: "154 WEST COAST ROAD MINDCHAMPS PRESCHOOL @ WEST COAST PLAZA PTE. LIMITED", lat: 1.303624575279406, lng: 103.7658583869225 },
  { id: "westgate", name: "Westgate", address: "3 GATEWAY DRIVE WESTGATE SINGAPORE 608532", lat: 1.334157675568678, lng: 103.7427664844237, carparkDevelopments: ["Westgate"] },
  { id: "west-mall", name: "West Mall", address: "1 BUKIT BATOK CENTRAL LINK WEST MALL SINGAPORE 658713", lat: 1.350021075943163, lng: 103.7492164938305 },
  { id: "yew-tee-point", name: "Yew Tee Point", address: "624 CHOA CHU KANG STREET 62 BESS POINT YEW TEE SQUARE", lat: 1.39803970584674, lng: 103.747197720839 },
  { id: "clarke-quay-central", name: "Clarke Quay Central", address: "6 EU TONG SEN STREET THE CENTRAL SINGAPORE 059817", lat: 1.288838562482049, lng: 103.8465580247433 },
  { id: "holland-village-shopping-mall", name: "Holland Village Shopping Mall", address: "19 LORONG LIPUT HOLLAND VILLAGE SINGAPORE 277732", lat: 1.310213107939612, lng: 103.795010190754 },
  { id: "shaw-house-and-centre", name: "Shaw House and Centre", address: "350 ORCHARD ROAD SHAW HOUSE SINGAPORE 238868", lat: 1.305809815805624, lng: 103.8315073656535 },
  { id: "novena-square-shopping-mall", name: "Novena Square Shopping Mall", address: "238 THOMSON ROAD NOVENA SQUARE SINGAPORE 307683", lat: 1.319967484391867, lng: 103.8438506309923 },
  { id: "i12-katong", name: "i12 Katong", address: "112 EAST COAST ROAD 112 KATONG SINGAPORE 428802", lat: 1.305206536173404, lng: 103.9050461102276 },
  { id: "ntu-north-spine-plaza", name: "NTU North Spine Plaza", address: "50 NANYANG AVENUE NANYANG TECHNOLOGICAL UNIVERSITY (NORTH SPINE) SINGAPORE 639798", lat: 1.346176496926749, lng: 103.6820489459634 },
  // Not on Wikipedia's mall list (not malls) but confirmed to have real
  // Popular Times coverage, and their LTA carpark records were otherwise
  // sitting unclaimed - added directly rather than through the Wikipedia
  // pipeline. Sentosa, Esplanade, and Resorts World Sentosa were tested the
  // same way and genuinely have no Popular Times data (Esplanade and
  // Sentosa resolve to the right Google Maps page but have no "Popular
  // times" section at all; Resorts World resolves to a hotel booking page
  // instead of the general attraction) - left out rather than shown with
  // nothing.
  { id: "the-heeren", name: "The Heeren", address: "260 ORCHARD ROAD THE HEEREN SINGAPORE 238855", lat: 1.30265, lng: 103.83737, carparkDevelopments: ["The Heeren"] },
  { id: "the-cathay", name: "The Cathay", address: "2 HANDY ROAD THE CATHAY SINGAPORE 229233", lat: 1.29921, lng: 103.84783, carparkDevelopments: ["The Cathay"] },
  { id: "singapore-flyer", name: "Singapore Flyer", address: "30 RAFFLES AVENUE SINGAPORE FLYER SINGAPORE 039803", lat: 1.28907, lng: 103.86292, carparkDevelopments: ["Singapore Flyer"] },
  { id: "national-gallery-singapore", name: "National Gallery Singapore", address: "1 SAINT ANDREW'S ROAD NATIONAL GALLERY SINGAPORE SINGAPORE 178957", lat: 1.29066, lng: 103.85171, carparkDevelopments: ["National Gallery"] },
];
